import { test } from "node:test";
import assert from "node:assert/strict";
import { arxivId, folderName, selectCards, explainerJson } from "../papers-lib.mjs";

const paper = { id: "20260913-2305-01210-gp2n", title: "Is Your Code Generated by ChatGPT Really Correct?",
  authors: ["Jiawei Liu", "Chunqiu Steven Xia", "Yuyao Wang", "Lingming Zhang"],
  source: { kind: "url", value: "https://arxiv.org/pdf/2305.01210.pdf" }, addedAt: "2026-09-13T20:58:34.402Z" };

test("arxivId handles pdf, abs, versioned, and non-arxiv", () => {
  assert.equal(arxivId("https://arxiv.org/pdf/2305.01210.pdf"), "2305.01210");
  assert.equal(arxivId("https://arxiv.org/abs/2107.03374v2"), "2107.03374");
  assert.equal(arxivId("/Users/me/paper.pdf"), null);
});

test("folderName prefers arxiv id, falls back to paper id", () => {
  assert.equal(folderName(paper), "paper-2305-01210");
  assert.equal(folderName({ ...paper, source: { value: "x.pdf" } }), "paper-20260913-2305-01210-gp2n");
});

test("selectCards: ready only, file must exist, overview first, revisions ignored", () => {
  const cards = { cards: [
    { slug: "pass-at-k", title: "pass@k", kind: "concept", status: "ready" },
    { slug: "_overview", title: "Overview", kind: "overview", status: "ready" },
    { slug: "drafting", title: "Drafting", kind: "concept", status: "generating" },
    { slug: "ghost", title: "Ghost", kind: "concept", status: "ready" },
  ] };
  const files = ["_overview.html", "pass-at-k.html", "pass-at-k.v1.html", "drafting.html"];
  assert.deepEqual(selectCards(cards, files).map((c) => c.file), ["_overview.html", "pass-at-k.html"]);
});

test("explainerJson builds description from authors and arxiv", () => {
  const j = explainerJson(paper, [{}, {}, {}]);
  assert.equal(j.kind, "paper");
  assert.equal(j.date, "2026-09-13");
  assert.equal(j.description, "Jiawei Liu, Chunqiu Steven Xia, Yuyao Wang et al. · arXiv 2305.01210");
  assert.equal(j.source, "https://arxiv.org/abs/2305.01210");
  assert.equal(j.cards, 3);
});
